--sql script to create database and tables
 USE master
GO
IF NOT EXISTS (
   SELECT name
   FROM sys.databases
   WHERE name = N'FoxTaskDB'
)
CREATE DATABASE [FoxTaskDB]
GO

 USE FoxTaskDB
 GO
 
 CREATE TABLE dbo.COURSES (
 COURSE_ID INT  NOT NULL PRIMARY KEY,
 NAME [NVARCHAR](255) NOT NULL,
 DESCRIPTION [TEXT]
 );
 GO
 
 CREATE TABLE dbo.GROUPS(
 GROUP_ID INT  NOT NULL PRIMARY KEY,
 COURSE_ID INT FOREIGN KEY REFERENCES COURSES (COURSE_ID), 
 NAME [NVARCHAR](MAX) NOT NULL
 );
 GO
 
 CREATE TABLE STUDENTS (
 STUDENT_ID INT NOT NULL PRIMARY KEY, 
 GROUP_ID INT FOREIGN KEY REFERENCES GROUPS (GROUP_ID), 
 FIRST_NAME [NVARCHAR](255) , 
 LAST_NAME [NVARCHAR](255)  NOT NULL
 );
 GO