--Write SQL query that finds name of course and related students

 USE FoxTaskDB
 GO
 
SELECT C.NAME, S.LAST_NAME
FROM COURSES C
JOIN  GROUPS G ON C.COURSE_ID = G.COURSE_ID 
JOIN  STUDENTS S ON  S.GROUP_ID = G.GROUP_ID
ORDER BY C.NAME